### ISSUE TITLE
Does wifi not work on this system?

### ISSUE THREAD

**Issue by btd1337** [EriHoss/TinkerRetroPie#6]
I'm trying to connect to wifi, but after putting the password in the retropie setting this connection always fails.

Does wifi not work on this system?

**Comment by AbiuPlayer** [comment]
write in english please.
For wifi from command line type sudo nmtui

**Comment by btd1337** [comment]
@AbiuPlayer Updated

**Comment by EriHoss** [comment]
Probably going to have to refer to Armbian documentation to get Wifi going using the console instead of the RetroPie script.

I have not tried Wifi honestly, but I wouldn't doubt that RetroPie's wifi setup script is doing something that is not valid on this platform.

I'll have to try later and get back to you here.

Sorry for late replys, I have not had much time lately.

**Comment by EriHoss** [comment]
was able to setup wifi using **armbian-config**, Armbians config tool which is installed by default.

Seems to be working.

```bash
sudo armbian-config

# Just ignore the internet connection warning if you currently have no Ethernet connection.
# It should still work.

# Go to: Network -> WiFi
# Select your SSID and enter password

```
